#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

#echo "This is a pre commit hook."
#echo "Before each commit this is executed and as soon as we have code, a test should be run to see is the code of this commit is working."
#echo "If the code is not working, the commit is aborted, so that you can fix it first."
#read -p "Press Enter to continue" </dev/tty

# Check client side if flutter is installed
if [ -f "$(which flutter)" ]; then
  echo "Check soTired app!"
  cd "${SCRIPT_DIR}"/../ || exit 1
  PRE_COMMIT_RESULT="$(make fluttercheck)"

  # Print if check was unsuccessful
  if [ $? != 0 ]; then
    echo "Failed Makefile output:"
    cat "$PRE_COMMIT_RESULT"
  fi
fi

# Check server side if go is installed
if [ -f "$(which go)" ]; then
  echo "Check soTired server!"
  cd "${SCRIPT_DIR}"/../ || exit 1
  PRE_COMMIT_RESULT="$(make gocheck)"

  # Print if check was unsuccessful
  if [ $? != 0 ]; then
    echo "Failed Makefile output:"
    cat "$PRE_COMMIT_RESULT"
  fi
fi
