name: soTired client/server validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test-build-client:
    name: Lint, test and build soTired app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Enable caching
        uses: actions/cache@v2
        with:
          path: |
            app/.dart_tool
            ~/.pub-cache
          key: ${{ runner.os }}-flutter_cache-${{ hashFiles('app/pubspec.lock') }}
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16.0.x'
          cache: 'gradle'
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - name: Check environment and install dependencies
        run: |
          flutter doctor -v
          make flutterget
      - name: Lint and run tests
        run: |
          make fluttercheck
          make fluttertest
      - name: Build Android app
        run: make flutterbuild
      - name: Archive Android app release
        uses: actions/upload-artifact@v2
        with:
          name: soTired Android app
          path: app/build/app/outputs/apk/release/app-release.apk
# NOTE: iOS build is disable because it can only be built on macOS devices
#      - name: Build iOS app
#        run: |
#          cd app
#          flutter build ios --release
#      - name: Archive iOS app release
#        uses: actions/upload-artifact@v2
#        with:
#          name: soTired iOS app
#          path:

  lint-test-build-server:
    name: Lint, test and build server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make gotidy
      - name: Lint
        run: make gocheck
      - name: Test
        run: make gotest
      - name: Build
        run: make gobuild
      - name: Archive server release
        uses: actions/upload-artifact@v2
        with:
          name: soTired server
          path: server/soti-server
