name: soTired client/server validation

#on: [push, pull_request]
on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test-client:
    name: Lint and test soTired app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Enable caching
#        uses: actions/cache@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16.0.x'
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - name: Check environment and install dependencies
        run: |
          cd app
          flutter doctor -v
          flutter pub get
      - name: Lint and run tests
        run: |
          cd app
          flutter analyze
          flutter test

  build-client:
    name: Build soTired app and save as artifact
    runs-on: ubuntu-latest
    needs: lint-and-test-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Enable caching
#        uses: actions/cache@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16.0.x'
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - name: Check environment and install dependencies
        run: |
          cd app
          flutter doctor -v
          flutter pub get
      - name: Build Android / iOS app
        run: |
          cd app
          flutter build apk
          flutter build ios --release
      - name: Archive Android app release
        uses: actions/upload-artifact@v2
        with:
          name: soTired Android app
          path: app/build/app/outputs/apk/release/app-release.apk
#      - name: Archive iOS app release
#        uses: actions/upload-artifact@v2
#        with:
#          name: soTired iOS app
#          path: 
